### ISSUE TITLE
Benchmark observation

### ISSUE THREAD

**Issue by MarkPflug** [pippinmole/CsvMole.NET#4]
I just wanted to point out that your use of the Sylvan libraries in the benchmarks isn't quite optimal. The `GetRecords` method in Sylvan.Data is a general-purpose binder for `DbDataReader`. As such, it can't make optimal use of CsvDataReader-specific behaviors. The binder expects that it must call Get[DataType] (GetString, GetDateTime, etc) based on the schema information reported by the DbDataReader. CSV data is un-typed, and so the CsvDataReader reports that the column type is `string` by default. However, you can call GetInt32, GetDateTime when the column is known to be a specific format: numeric, date, etc. Most DbDataReaders don't allow that. SqlDataReader, for example, would throw if you called GetInt32 on a string column containing the string "123".

As such, it would be more optimal to not use the Sylvan.Data library as a helper in this case, and instead handle the binding manually as you did with the Sep library:

```
    [Benchmark]
    public List<CsvHelperSylvan> SylvanParse()
    {
        using var textReader = new StringReader(_content);
        using var dr = Sylvan.Data.Csv.CsvDataReader.Create(textReader);

        var list = new List<CsvHelperSylvan>();
        while (dr.Read())
        {
            list.Add(
                new CsvHelperSylvan
                {
                    Id = dr.GetString(0),
                    Date = dr.GetDateTime(1)
                }
            );
        }

        return list;
    }
```
There are ways to make the Sylvan.Data binder work optimally in this case, by either specifying a schema for the CsvDataReader, or configuring how the binder operates, but for this example it's easier to just bind manually. 

With that change Sylvan is basically equivalent with Sep in performance and memory (on my machine).

I also have a fast-path for ISO8601 formatted dates, which is the default format that Sylvan would write, so the performance is significantly improved if you create the CSV data in that format:

```
_content += $"{i},{DateTime.Now:yyyy-MM-dd HH:mm:ss}\n";
```
With this change Sylvan is a bit faster than Sep, probably one of the few scenarios where it would be.

Cool project. I've found the source generator APIs to be hard to understand, so I'll be interested in studying your code.

**Comment by pippinmole** [comment]
Hi Mark,

First of all, thanks for taking time to make an issue. This project is very early days but it's really nice to see some interaction.

On your point about optimizations - you're correct. I only really have the benchmarks as a rough guestimate at this time, but I can see some major improvements in performance, especially with the date time fast-path:

![image](https://github.com/pippinmole/CsvMole.NET/assets/40035529/3fb0efb4-fe7e-478a-b2e3-01537fcab796)

I'm going to add the fast-path alongside the initial DateTime, just because not all fields will match that exact fast-path format.

> I've found the source generator APIs to be hard to understand

Yes, me and you both. It's quite tricky to debug errors in analyzers, especially because `Console.WriteLine` doesn't work like in normal code (and debugging doesn't work).

Thank you again for leaving feedback :)
